version: '3.8'

services:
  gpt-researcher:
    build: .
    ports:
      - "5001:5001"
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./server/.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - server/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health && curl -f http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
